export const API = {
  preferences: "/api/preferences",
  circular: "/api/circular",
  circularPrefs: "/api/circular/prefs",
  circularProgress: "/api/circular/progress",
  circularUpload: "/api/circular/upload",
  circularFlippStores: "/api/circular/flipp/stores",
  circularFlippFetch: "/api/circular/flipp/fetch",
  mealPlan: "/api/meal-plan",
  mealPlanGenerate: "/api/meal-plan/generate",
  mealPlanGenerateNoCircular: "/api/meal-plan/generate-no-circular",
  mealPlanSwap: "/api/meal-plan/swap",
  mealPlanMove: "/api/meal-plan/move",
  shoppingListState: "/api/shopping-list-state",
} as const;
